# Generated by Django 4.0 on 2021-12-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_geolocation_accesspoint_geolocation'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(help_text='company to which the user belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
