# Generated by Django 4.0 on 2021-12-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrator', to='users.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(related_name='employees', through='companies.Employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='company',
            field=models.ForeignKey(help_text='company to which the user belongs', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='accesshour',
            name='access_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.accesspoint'),
        ),
        migrations.AddField(
            model_name='accesshour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
