# Generated by Django 4.0 on 2021-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_geolocation_accesspoint_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesshour',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
